name = "your-next-app"
main = ".opennext/worker/index.js"
account_id="4a4d21018db00cc3cf88a4b67d70b6cf"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://dqxoiudeespmrocafyip.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."